---
global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: relayer
    # Prometheus uses this api path to scrape metrics from the relayer container
    metrics_path: /debug/metrics/scrape
    scheme: http
    static_configs:
      - targets:
          - relayer:8081
  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis-exporter:9121
