---
global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: monitor
    # Prometheus uses this api path to scrape metrics from the monitor container
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - monitor:8081
