[build]
base = "/"
command = "rustup default stable && cargo install cargo-make --locked --force && cd docs && npm ci && npm run docs && cd .. && cargo make rust-antora"
publish = "docs/build/site"

[build.environment]
PKG_CONFIG_PATH = "/home/linuxbrew/.linuxbrew/lib/pkgconfig"
